# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sam/Documents/Brambles

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sam/Documents/Brambles/build-emscripten

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sam/Documents/Brambles/build-emscripten/CMakeFiles /home/sam/Documents/Brambles/build-emscripten//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sam/Documents/Brambles/build-emscripten/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sam/Documents/Brambles/build-emscripten/CMakeFiles /home/sam/Documents/Brambles/build-emscripten//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sam/Documents/Brambles/build-emscripten/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named demo

# Build rule for target.
demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo
.PHONY : demo

# fast build rule for target.
demo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/build
.PHONY : demo/fast

#=============================================================================
# Target rules for targets named rend

# Build rule for target.
rend: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rend
.PHONY : rend

# fast build rule for target.
rend/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rend.dir/build.make CMakeFiles/rend.dir/build
.PHONY : rend/fast

#=============================================================================
# Target rules for targets named Brambles

# Build rule for target.
Brambles: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Brambles
.PHONY : Brambles

# fast build rule for target.
Brambles/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/build
.PHONY : Brambles/fast

src/Brambles/AudioSource.o: src/Brambles/AudioSource.cpp.o
.PHONY : src/Brambles/AudioSource.o

# target to build an object file
src/Brambles/AudioSource.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/AudioSource.cpp.o
.PHONY : src/Brambles/AudioSource.cpp.o

src/Brambles/AudioSource.i: src/Brambles/AudioSource.cpp.i
.PHONY : src/Brambles/AudioSource.i

# target to preprocess a source file
src/Brambles/AudioSource.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/AudioSource.cpp.i
.PHONY : src/Brambles/AudioSource.cpp.i

src/Brambles/AudioSource.s: src/Brambles/AudioSource.cpp.s
.PHONY : src/Brambles/AudioSource.s

# target to generate assembly for a file
src/Brambles/AudioSource.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/AudioSource.cpp.s
.PHONY : src/Brambles/AudioSource.cpp.s

src/Brambles/BoxCollider.o: src/Brambles/BoxCollider.cpp.o
.PHONY : src/Brambles/BoxCollider.o

# target to build an object file
src/Brambles/BoxCollider.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/BoxCollider.cpp.o
.PHONY : src/Brambles/BoxCollider.cpp.o

src/Brambles/BoxCollider.i: src/Brambles/BoxCollider.cpp.i
.PHONY : src/Brambles/BoxCollider.i

# target to preprocess a source file
src/Brambles/BoxCollider.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/BoxCollider.cpp.i
.PHONY : src/Brambles/BoxCollider.cpp.i

src/Brambles/BoxCollider.s: src/Brambles/BoxCollider.cpp.s
.PHONY : src/Brambles/BoxCollider.s

# target to generate assembly for a file
src/Brambles/BoxCollider.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/BoxCollider.cpp.s
.PHONY : src/Brambles/BoxCollider.cpp.s

src/Brambles/Camera.o: src/Brambles/Camera.cpp.o
.PHONY : src/Brambles/Camera.o

# target to build an object file
src/Brambles/Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Camera.cpp.o
.PHONY : src/Brambles/Camera.cpp.o

src/Brambles/Camera.i: src/Brambles/Camera.cpp.i
.PHONY : src/Brambles/Camera.i

# target to preprocess a source file
src/Brambles/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Camera.cpp.i
.PHONY : src/Brambles/Camera.cpp.i

src/Brambles/Camera.s: src/Brambles/Camera.cpp.s
.PHONY : src/Brambles/Camera.s

# target to generate assembly for a file
src/Brambles/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Camera.cpp.s
.PHONY : src/Brambles/Camera.cpp.s

src/Brambles/Component.o: src/Brambles/Component.cpp.o
.PHONY : src/Brambles/Component.o

# target to build an object file
src/Brambles/Component.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Component.cpp.o
.PHONY : src/Brambles/Component.cpp.o

src/Brambles/Component.i: src/Brambles/Component.cpp.i
.PHONY : src/Brambles/Component.i

# target to preprocess a source file
src/Brambles/Component.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Component.cpp.i
.PHONY : src/Brambles/Component.cpp.i

src/Brambles/Component.s: src/Brambles/Component.cpp.s
.PHONY : src/Brambles/Component.s

# target to generate assembly for a file
src/Brambles/Component.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Component.cpp.s
.PHONY : src/Brambles/Component.cpp.s

src/Brambles/Controllers/CameraController.o: src/Brambles/Controllers/CameraController.cpp.o
.PHONY : src/Brambles/Controllers/CameraController.o

# target to build an object file
src/Brambles/Controllers/CameraController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Controllers/CameraController.cpp.o
.PHONY : src/Brambles/Controllers/CameraController.cpp.o

src/Brambles/Controllers/CameraController.i: src/Brambles/Controllers/CameraController.cpp.i
.PHONY : src/Brambles/Controllers/CameraController.i

# target to preprocess a source file
src/Brambles/Controllers/CameraController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Controllers/CameraController.cpp.i
.PHONY : src/Brambles/Controllers/CameraController.cpp.i

src/Brambles/Controllers/CameraController.s: src/Brambles/Controllers/CameraController.cpp.s
.PHONY : src/Brambles/Controllers/CameraController.s

# target to generate assembly for a file
src/Brambles/Controllers/CameraController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Controllers/CameraController.cpp.s
.PHONY : src/Brambles/Controllers/CameraController.cpp.s

src/Brambles/Controllers/PlayerController.o: src/Brambles/Controllers/PlayerController.cpp.o
.PHONY : src/Brambles/Controllers/PlayerController.o

# target to build an object file
src/Brambles/Controllers/PlayerController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Controllers/PlayerController.cpp.o
.PHONY : src/Brambles/Controllers/PlayerController.cpp.o

src/Brambles/Controllers/PlayerController.i: src/Brambles/Controllers/PlayerController.cpp.i
.PHONY : src/Brambles/Controllers/PlayerController.i

# target to preprocess a source file
src/Brambles/Controllers/PlayerController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Controllers/PlayerController.cpp.i
.PHONY : src/Brambles/Controllers/PlayerController.cpp.i

src/Brambles/Controllers/PlayerController.s: src/Brambles/Controllers/PlayerController.cpp.s
.PHONY : src/Brambles/Controllers/PlayerController.s

# target to generate assembly for a file
src/Brambles/Controllers/PlayerController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Controllers/PlayerController.cpp.s
.PHONY : src/Brambles/Controllers/PlayerController.cpp.s

src/Brambles/Core.o: src/Brambles/Core.cpp.o
.PHONY : src/Brambles/Core.o

# target to build an object file
src/Brambles/Core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Core.cpp.o
.PHONY : src/Brambles/Core.cpp.o

src/Brambles/Core.i: src/Brambles/Core.cpp.i
.PHONY : src/Brambles/Core.i

# target to preprocess a source file
src/Brambles/Core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Core.cpp.i
.PHONY : src/Brambles/Core.cpp.i

src/Brambles/Core.s: src/Brambles/Core.cpp.s
.PHONY : src/Brambles/Core.s

# target to generate assembly for a file
src/Brambles/Core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Core.cpp.s
.PHONY : src/Brambles/Core.cpp.s

src/Brambles/DebugRenderer.o: src/Brambles/DebugRenderer.cpp.o
.PHONY : src/Brambles/DebugRenderer.o

# target to build an object file
src/Brambles/DebugRenderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/DebugRenderer.cpp.o
.PHONY : src/Brambles/DebugRenderer.cpp.o

src/Brambles/DebugRenderer.i: src/Brambles/DebugRenderer.cpp.i
.PHONY : src/Brambles/DebugRenderer.i

# target to preprocess a source file
src/Brambles/DebugRenderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/DebugRenderer.cpp.i
.PHONY : src/Brambles/DebugRenderer.cpp.i

src/Brambles/DebugRenderer.s: src/Brambles/DebugRenderer.cpp.s
.PHONY : src/Brambles/DebugRenderer.s

# target to generate assembly for a file
src/Brambles/DebugRenderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/DebugRenderer.cpp.s
.PHONY : src/Brambles/DebugRenderer.cpp.s

src/Brambles/Entity.o: src/Brambles/Entity.cpp.o
.PHONY : src/Brambles/Entity.o

# target to build an object file
src/Brambles/Entity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Entity.cpp.o
.PHONY : src/Brambles/Entity.cpp.o

src/Brambles/Entity.i: src/Brambles/Entity.cpp.i
.PHONY : src/Brambles/Entity.i

# target to preprocess a source file
src/Brambles/Entity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Entity.cpp.i
.PHONY : src/Brambles/Entity.cpp.i

src/Brambles/Entity.s: src/Brambles/Entity.cpp.s
.PHONY : src/Brambles/Entity.s

# target to generate assembly for a file
src/Brambles/Entity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Entity.cpp.s
.PHONY : src/Brambles/Entity.cpp.s

src/Brambles/Gui.o: src/Brambles/Gui.cpp.o
.PHONY : src/Brambles/Gui.o

# target to build an object file
src/Brambles/Gui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Gui.cpp.o
.PHONY : src/Brambles/Gui.cpp.o

src/Brambles/Gui.i: src/Brambles/Gui.cpp.i
.PHONY : src/Brambles/Gui.i

# target to preprocess a source file
src/Brambles/Gui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Gui.cpp.i
.PHONY : src/Brambles/Gui.cpp.i

src/Brambles/Gui.s: src/Brambles/Gui.cpp.s
.PHONY : src/Brambles/Gui.s

# target to generate assembly for a file
src/Brambles/Gui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Gui.cpp.s
.PHONY : src/Brambles/Gui.cpp.s

src/Brambles/Input.o: src/Brambles/Input.cpp.o
.PHONY : src/Brambles/Input.o

# target to build an object file
src/Brambles/Input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Input.cpp.o
.PHONY : src/Brambles/Input.cpp.o

src/Brambles/Input.i: src/Brambles/Input.cpp.i
.PHONY : src/Brambles/Input.i

# target to preprocess a source file
src/Brambles/Input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Input.cpp.i
.PHONY : src/Brambles/Input.cpp.i

src/Brambles/Input.s: src/Brambles/Input.cpp.s
.PHONY : src/Brambles/Input.s

# target to generate assembly for a file
src/Brambles/Input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Input.cpp.s
.PHONY : src/Brambles/Input.cpp.s

src/Brambles/MeshCollider.o: src/Brambles/MeshCollider.cpp.o
.PHONY : src/Brambles/MeshCollider.o

# target to build an object file
src/Brambles/MeshCollider.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/MeshCollider.cpp.o
.PHONY : src/Brambles/MeshCollider.cpp.o

src/Brambles/MeshCollider.i: src/Brambles/MeshCollider.cpp.i
.PHONY : src/Brambles/MeshCollider.i

# target to preprocess a source file
src/Brambles/MeshCollider.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/MeshCollider.cpp.i
.PHONY : src/Brambles/MeshCollider.cpp.i

src/Brambles/MeshCollider.s: src/Brambles/MeshCollider.cpp.s
.PHONY : src/Brambles/MeshCollider.s

# target to generate assembly for a file
src/Brambles/MeshCollider.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/MeshCollider.cpp.s
.PHONY : src/Brambles/MeshCollider.cpp.s

src/Brambles/Physics.o: src/Brambles/Physics.cpp.o
.PHONY : src/Brambles/Physics.o

# target to build an object file
src/Brambles/Physics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Physics.cpp.o
.PHONY : src/Brambles/Physics.cpp.o

src/Brambles/Physics.i: src/Brambles/Physics.cpp.i
.PHONY : src/Brambles/Physics.i

# target to preprocess a source file
src/Brambles/Physics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Physics.cpp.i
.PHONY : src/Brambles/Physics.cpp.i

src/Brambles/Physics.s: src/Brambles/Physics.cpp.s
.PHONY : src/Brambles/Physics.s

# target to generate assembly for a file
src/Brambles/Physics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Physics.cpp.s
.PHONY : src/Brambles/Physics.cpp.s

src/Brambles/Renderer.o: src/Brambles/Renderer.cpp.o
.PHONY : src/Brambles/Renderer.o

# target to build an object file
src/Brambles/Renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Renderer.cpp.o
.PHONY : src/Brambles/Renderer.cpp.o

src/Brambles/Renderer.i: src/Brambles/Renderer.cpp.i
.PHONY : src/Brambles/Renderer.i

# target to preprocess a source file
src/Brambles/Renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Renderer.cpp.i
.PHONY : src/Brambles/Renderer.cpp.i

src/Brambles/Renderer.s: src/Brambles/Renderer.cpp.s
.PHONY : src/Brambles/Renderer.s

# target to generate assembly for a file
src/Brambles/Renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Renderer.cpp.s
.PHONY : src/Brambles/Renderer.cpp.s

src/Brambles/Resource.o: src/Brambles/Resource.cpp.o
.PHONY : src/Brambles/Resource.o

# target to build an object file
src/Brambles/Resource.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Resource.cpp.o
.PHONY : src/Brambles/Resource.cpp.o

src/Brambles/Resource.i: src/Brambles/Resource.cpp.i
.PHONY : src/Brambles/Resource.i

# target to preprocess a source file
src/Brambles/Resource.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Resource.cpp.i
.PHONY : src/Brambles/Resource.cpp.i

src/Brambles/Resource.s: src/Brambles/Resource.cpp.s
.PHONY : src/Brambles/Resource.s

# target to generate assembly for a file
src/Brambles/Resource.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Resource.cpp.s
.PHONY : src/Brambles/Resource.cpp.s

src/Brambles/Resources/Audio.o: src/Brambles/Resources/Audio.cpp.o
.PHONY : src/Brambles/Resources/Audio.o

# target to build an object file
src/Brambles/Resources/Audio.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Resources/Audio.cpp.o
.PHONY : src/Brambles/Resources/Audio.cpp.o

src/Brambles/Resources/Audio.i: src/Brambles/Resources/Audio.cpp.i
.PHONY : src/Brambles/Resources/Audio.i

# target to preprocess a source file
src/Brambles/Resources/Audio.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Resources/Audio.cpp.i
.PHONY : src/Brambles/Resources/Audio.cpp.i

src/Brambles/Resources/Audio.s: src/Brambles/Resources/Audio.cpp.s
.PHONY : src/Brambles/Resources/Audio.s

# target to generate assembly for a file
src/Brambles/Resources/Audio.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Resources/Audio.cpp.s
.PHONY : src/Brambles/Resources/Audio.cpp.s

src/Brambles/Resources/Model.o: src/Brambles/Resources/Model.cpp.o
.PHONY : src/Brambles/Resources/Model.o

# target to build an object file
src/Brambles/Resources/Model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Resources/Model.cpp.o
.PHONY : src/Brambles/Resources/Model.cpp.o

src/Brambles/Resources/Model.i: src/Brambles/Resources/Model.cpp.i
.PHONY : src/Brambles/Resources/Model.i

# target to preprocess a source file
src/Brambles/Resources/Model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Resources/Model.cpp.i
.PHONY : src/Brambles/Resources/Model.cpp.i

src/Brambles/Resources/Model.s: src/Brambles/Resources/Model.cpp.s
.PHONY : src/Brambles/Resources/Model.s

# target to generate assembly for a file
src/Brambles/Resources/Model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Resources/Model.cpp.s
.PHONY : src/Brambles/Resources/Model.cpp.s

src/Brambles/Resources/Shader.o: src/Brambles/Resources/Shader.cpp.o
.PHONY : src/Brambles/Resources/Shader.o

# target to build an object file
src/Brambles/Resources/Shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Resources/Shader.cpp.o
.PHONY : src/Brambles/Resources/Shader.cpp.o

src/Brambles/Resources/Shader.i: src/Brambles/Resources/Shader.cpp.i
.PHONY : src/Brambles/Resources/Shader.i

# target to preprocess a source file
src/Brambles/Resources/Shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Resources/Shader.cpp.i
.PHONY : src/Brambles/Resources/Shader.cpp.i

src/Brambles/Resources/Shader.s: src/Brambles/Resources/Shader.cpp.s
.PHONY : src/Brambles/Resources/Shader.s

# target to generate assembly for a file
src/Brambles/Resources/Shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Resources/Shader.cpp.s
.PHONY : src/Brambles/Resources/Shader.cpp.s

src/Brambles/Resources/Texture.o: src/Brambles/Resources/Texture.cpp.o
.PHONY : src/Brambles/Resources/Texture.o

# target to build an object file
src/Brambles/Resources/Texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Resources/Texture.cpp.o
.PHONY : src/Brambles/Resources/Texture.cpp.o

src/Brambles/Resources/Texture.i: src/Brambles/Resources/Texture.cpp.i
.PHONY : src/Brambles/Resources/Texture.i

# target to preprocess a source file
src/Brambles/Resources/Texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Resources/Texture.cpp.i
.PHONY : src/Brambles/Resources/Texture.cpp.i

src/Brambles/Resources/Texture.s: src/Brambles/Resources/Texture.cpp.s
.PHONY : src/Brambles/Resources/Texture.s

# target to generate assembly for a file
src/Brambles/Resources/Texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Resources/Texture.cpp.s
.PHONY : src/Brambles/Resources/Texture.cpp.s

src/Brambles/RigidBody.o: src/Brambles/RigidBody.cpp.o
.PHONY : src/Brambles/RigidBody.o

# target to build an object file
src/Brambles/RigidBody.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/RigidBody.cpp.o
.PHONY : src/Brambles/RigidBody.cpp.o

src/Brambles/RigidBody.i: src/Brambles/RigidBody.cpp.i
.PHONY : src/Brambles/RigidBody.i

# target to preprocess a source file
src/Brambles/RigidBody.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/RigidBody.cpp.i
.PHONY : src/Brambles/RigidBody.cpp.i

src/Brambles/RigidBody.s: src/Brambles/RigidBody.cpp.s
.PHONY : src/Brambles/RigidBody.s

# target to generate assembly for a file
src/Brambles/RigidBody.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/RigidBody.cpp.s
.PHONY : src/Brambles/RigidBody.cpp.s

src/Brambles/Sound.o: src/Brambles/Sound.cpp.o
.PHONY : src/Brambles/Sound.o

# target to build an object file
src/Brambles/Sound.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Sound.cpp.o
.PHONY : src/Brambles/Sound.cpp.o

src/Brambles/Sound.i: src/Brambles/Sound.cpp.i
.PHONY : src/Brambles/Sound.i

# target to preprocess a source file
src/Brambles/Sound.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Sound.cpp.i
.PHONY : src/Brambles/Sound.cpp.i

src/Brambles/Sound.s: src/Brambles/Sound.cpp.s
.PHONY : src/Brambles/Sound.s

# target to generate assembly for a file
src/Brambles/Sound.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Sound.cpp.s
.PHONY : src/Brambles/Sound.cpp.s

src/Brambles/Timer.o: src/Brambles/Timer.cpp.o
.PHONY : src/Brambles/Timer.o

# target to build an object file
src/Brambles/Timer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Timer.cpp.o
.PHONY : src/Brambles/Timer.cpp.o

src/Brambles/Timer.i: src/Brambles/Timer.cpp.i
.PHONY : src/Brambles/Timer.i

# target to preprocess a source file
src/Brambles/Timer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Timer.cpp.i
.PHONY : src/Brambles/Timer.cpp.i

src/Brambles/Timer.s: src/Brambles/Timer.cpp.s
.PHONY : src/Brambles/Timer.s

# target to generate assembly for a file
src/Brambles/Timer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Timer.cpp.s
.PHONY : src/Brambles/Timer.cpp.s

src/Brambles/Transform.o: src/Brambles/Transform.cpp.o
.PHONY : src/Brambles/Transform.o

# target to build an object file
src/Brambles/Transform.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Transform.cpp.o
.PHONY : src/Brambles/Transform.cpp.o

src/Brambles/Transform.i: src/Brambles/Transform.cpp.i
.PHONY : src/Brambles/Transform.i

# target to preprocess a source file
src/Brambles/Transform.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Transform.cpp.i
.PHONY : src/Brambles/Transform.cpp.i

src/Brambles/Transform.s: src/Brambles/Transform.cpp.s
.PHONY : src/Brambles/Transform.s

# target to generate assembly for a file
src/Brambles/Transform.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Transform.cpp.s
.PHONY : src/Brambles/Transform.cpp.s

src/Brambles/Window.o: src/Brambles/Window.cpp.o
.PHONY : src/Brambles/Window.o

# target to build an object file
src/Brambles/Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Window.cpp.o
.PHONY : src/Brambles/Window.cpp.o

src/Brambles/Window.i: src/Brambles/Window.cpp.i
.PHONY : src/Brambles/Window.i

# target to preprocess a source file
src/Brambles/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Window.cpp.i
.PHONY : src/Brambles/Window.cpp.i

src/Brambles/Window.s: src/Brambles/Window.cpp.s
.PHONY : src/Brambles/Window.s

# target to generate assembly for a file
src/Brambles/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brambles.dir/build.make CMakeFiles/Brambles.dir/src/Brambles/Window.cpp.s
.PHONY : src/Brambles/Window.cpp.s

src/demo/main.o: src/demo/main.cpp.o
.PHONY : src/demo/main.o

# target to build an object file
src/demo/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/src/demo/main.cpp.o
.PHONY : src/demo/main.cpp.o

src/demo/main.i: src/demo/main.cpp.i
.PHONY : src/demo/main.i

# target to preprocess a source file
src/demo/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/src/demo/main.cpp.i
.PHONY : src/demo/main.cpp.i

src/demo/main.s: src/demo/main.cpp.s
.PHONY : src/demo/main.s

# target to generate assembly for a file
src/demo/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/src/demo/main.cpp.s
.PHONY : src/demo/main.cpp.s

src/rend/Font.o: src/rend/Font.cpp.o
.PHONY : src/rend/Font.o

# target to build an object file
src/rend/Font.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rend.dir/build.make CMakeFiles/rend.dir/src/rend/Font.cpp.o
.PHONY : src/rend/Font.cpp.o

src/rend/Font.i: src/rend/Font.cpp.i
.PHONY : src/rend/Font.i

# target to preprocess a source file
src/rend/Font.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rend.dir/build.make CMakeFiles/rend.dir/src/rend/Font.cpp.i
.PHONY : src/rend/Font.cpp.i

src/rend/Font.s: src/rend/Font.cpp.s
.PHONY : src/rend/Font.s

# target to generate assembly for a file
src/rend/Font.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rend.dir/build.make CMakeFiles/rend.dir/src/rend/Font.cpp.s
.PHONY : src/rend/Font.cpp.s

src/rend/Mesh.o: src/rend/Mesh.cpp.o
.PHONY : src/rend/Mesh.o

# target to build an object file
src/rend/Mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rend.dir/build.make CMakeFiles/rend.dir/src/rend/Mesh.cpp.o
.PHONY : src/rend/Mesh.cpp.o

src/rend/Mesh.i: src/rend/Mesh.cpp.i
.PHONY : src/rend/Mesh.i

# target to preprocess a source file
src/rend/Mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rend.dir/build.make CMakeFiles/rend.dir/src/rend/Mesh.cpp.i
.PHONY : src/rend/Mesh.cpp.i

src/rend/Mesh.s: src/rend/Mesh.cpp.s
.PHONY : src/rend/Mesh.s

# target to generate assembly for a file
src/rend/Mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rend.dir/build.make CMakeFiles/rend.dir/src/rend/Mesh.cpp.s
.PHONY : src/rend/Mesh.cpp.s

src/rend/Model.o: src/rend/Model.cpp.o
.PHONY : src/rend/Model.o

# target to build an object file
src/rend/Model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rend.dir/build.make CMakeFiles/rend.dir/src/rend/Model.cpp.o
.PHONY : src/rend/Model.cpp.o

src/rend/Model.i: src/rend/Model.cpp.i
.PHONY : src/rend/Model.i

# target to preprocess a source file
src/rend/Model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rend.dir/build.make CMakeFiles/rend.dir/src/rend/Model.cpp.i
.PHONY : src/rend/Model.cpp.i

src/rend/Model.s: src/rend/Model.cpp.s
.PHONY : src/rend/Model.s

# target to generate assembly for a file
src/rend/Model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rend.dir/build.make CMakeFiles/rend.dir/src/rend/Model.cpp.s
.PHONY : src/rend/Model.cpp.s

src/rend/RenderTexture.o: src/rend/RenderTexture.cpp.o
.PHONY : src/rend/RenderTexture.o

# target to build an object file
src/rend/RenderTexture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rend.dir/build.make CMakeFiles/rend.dir/src/rend/RenderTexture.cpp.o
.PHONY : src/rend/RenderTexture.cpp.o

src/rend/RenderTexture.i: src/rend/RenderTexture.cpp.i
.PHONY : src/rend/RenderTexture.i

# target to preprocess a source file
src/rend/RenderTexture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rend.dir/build.make CMakeFiles/rend.dir/src/rend/RenderTexture.cpp.i
.PHONY : src/rend/RenderTexture.cpp.i

src/rend/RenderTexture.s: src/rend/RenderTexture.cpp.s
.PHONY : src/rend/RenderTexture.s

# target to generate assembly for a file
src/rend/RenderTexture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rend.dir/build.make CMakeFiles/rend.dir/src/rend/RenderTexture.cpp.s
.PHONY : src/rend/RenderTexture.cpp.s

src/rend/Shader.o: src/rend/Shader.cpp.o
.PHONY : src/rend/Shader.o

# target to build an object file
src/rend/Shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rend.dir/build.make CMakeFiles/rend.dir/src/rend/Shader.cpp.o
.PHONY : src/rend/Shader.cpp.o

src/rend/Shader.i: src/rend/Shader.cpp.i
.PHONY : src/rend/Shader.i

# target to preprocess a source file
src/rend/Shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rend.dir/build.make CMakeFiles/rend.dir/src/rend/Shader.cpp.i
.PHONY : src/rend/Shader.cpp.i

src/rend/Shader.s: src/rend/Shader.cpp.s
.PHONY : src/rend/Shader.s

# target to generate assembly for a file
src/rend/Shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rend.dir/build.make CMakeFiles/rend.dir/src/rend/Shader.cpp.s
.PHONY : src/rend/Shader.cpp.s

src/rend/Texture.o: src/rend/Texture.cpp.o
.PHONY : src/rend/Texture.o

# target to build an object file
src/rend/Texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rend.dir/build.make CMakeFiles/rend.dir/src/rend/Texture.cpp.o
.PHONY : src/rend/Texture.cpp.o

src/rend/Texture.i: src/rend/Texture.cpp.i
.PHONY : src/rend/Texture.i

# target to preprocess a source file
src/rend/Texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rend.dir/build.make CMakeFiles/rend.dir/src/rend/Texture.cpp.i
.PHONY : src/rend/Texture.cpp.i

src/rend/Texture.s: src/rend/Texture.cpp.s
.PHONY : src/rend/Texture.s

# target to generate assembly for a file
src/rend/Texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rend.dir/build.make CMakeFiles/rend.dir/src/rend/Texture.cpp.s
.PHONY : src/rend/Texture.cpp.s

src/rend/Utilities.o: src/rend/Utilities.cpp.o
.PHONY : src/rend/Utilities.o

# target to build an object file
src/rend/Utilities.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rend.dir/build.make CMakeFiles/rend.dir/src/rend/Utilities.cpp.o
.PHONY : src/rend/Utilities.cpp.o

src/rend/Utilities.i: src/rend/Utilities.cpp.i
.PHONY : src/rend/Utilities.i

# target to preprocess a source file
src/rend/Utilities.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rend.dir/build.make CMakeFiles/rend.dir/src/rend/Utilities.cpp.i
.PHONY : src/rend/Utilities.cpp.i

src/rend/Utilities.s: src/rend/Utilities.cpp.s
.PHONY : src/rend/Utilities.s

# target to generate assembly for a file
src/rend/Utilities.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rend.dir/build.make CMakeFiles/rend.dir/src/rend/Utilities.cpp.s
.PHONY : src/rend/Utilities.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Brambles"
	@echo "... demo"
	@echo "... rend"
	@echo "... src/Brambles/AudioSource.o"
	@echo "... src/Brambles/AudioSource.i"
	@echo "... src/Brambles/AudioSource.s"
	@echo "... src/Brambles/BoxCollider.o"
	@echo "... src/Brambles/BoxCollider.i"
	@echo "... src/Brambles/BoxCollider.s"
	@echo "... src/Brambles/Camera.o"
	@echo "... src/Brambles/Camera.i"
	@echo "... src/Brambles/Camera.s"
	@echo "... src/Brambles/Component.o"
	@echo "... src/Brambles/Component.i"
	@echo "... src/Brambles/Component.s"
	@echo "... src/Brambles/Controllers/CameraController.o"
	@echo "... src/Brambles/Controllers/CameraController.i"
	@echo "... src/Brambles/Controllers/CameraController.s"
	@echo "... src/Brambles/Controllers/PlayerController.o"
	@echo "... src/Brambles/Controllers/PlayerController.i"
	@echo "... src/Brambles/Controllers/PlayerController.s"
	@echo "... src/Brambles/Core.o"
	@echo "... src/Brambles/Core.i"
	@echo "... src/Brambles/Core.s"
	@echo "... src/Brambles/DebugRenderer.o"
	@echo "... src/Brambles/DebugRenderer.i"
	@echo "... src/Brambles/DebugRenderer.s"
	@echo "... src/Brambles/Entity.o"
	@echo "... src/Brambles/Entity.i"
	@echo "... src/Brambles/Entity.s"
	@echo "... src/Brambles/Gui.o"
	@echo "... src/Brambles/Gui.i"
	@echo "... src/Brambles/Gui.s"
	@echo "... src/Brambles/Input.o"
	@echo "... src/Brambles/Input.i"
	@echo "... src/Brambles/Input.s"
	@echo "... src/Brambles/MeshCollider.o"
	@echo "... src/Brambles/MeshCollider.i"
	@echo "... src/Brambles/MeshCollider.s"
	@echo "... src/Brambles/Physics.o"
	@echo "... src/Brambles/Physics.i"
	@echo "... src/Brambles/Physics.s"
	@echo "... src/Brambles/Renderer.o"
	@echo "... src/Brambles/Renderer.i"
	@echo "... src/Brambles/Renderer.s"
	@echo "... src/Brambles/Resource.o"
	@echo "... src/Brambles/Resource.i"
	@echo "... src/Brambles/Resource.s"
	@echo "... src/Brambles/Resources/Audio.o"
	@echo "... src/Brambles/Resources/Audio.i"
	@echo "... src/Brambles/Resources/Audio.s"
	@echo "... src/Brambles/Resources/Model.o"
	@echo "... src/Brambles/Resources/Model.i"
	@echo "... src/Brambles/Resources/Model.s"
	@echo "... src/Brambles/Resources/Shader.o"
	@echo "... src/Brambles/Resources/Shader.i"
	@echo "... src/Brambles/Resources/Shader.s"
	@echo "... src/Brambles/Resources/Texture.o"
	@echo "... src/Brambles/Resources/Texture.i"
	@echo "... src/Brambles/Resources/Texture.s"
	@echo "... src/Brambles/RigidBody.o"
	@echo "... src/Brambles/RigidBody.i"
	@echo "... src/Brambles/RigidBody.s"
	@echo "... src/Brambles/Sound.o"
	@echo "... src/Brambles/Sound.i"
	@echo "... src/Brambles/Sound.s"
	@echo "... src/Brambles/Timer.o"
	@echo "... src/Brambles/Timer.i"
	@echo "... src/Brambles/Timer.s"
	@echo "... src/Brambles/Transform.o"
	@echo "... src/Brambles/Transform.i"
	@echo "... src/Brambles/Transform.s"
	@echo "... src/Brambles/Window.o"
	@echo "... src/Brambles/Window.i"
	@echo "... src/Brambles/Window.s"
	@echo "... src/demo/main.o"
	@echo "... src/demo/main.i"
	@echo "... src/demo/main.s"
	@echo "... src/rend/Font.o"
	@echo "... src/rend/Font.i"
	@echo "... src/rend/Font.s"
	@echo "... src/rend/Mesh.o"
	@echo "... src/rend/Mesh.i"
	@echo "... src/rend/Mesh.s"
	@echo "... src/rend/Model.o"
	@echo "... src/rend/Model.i"
	@echo "... src/rend/Model.s"
	@echo "... src/rend/RenderTexture.o"
	@echo "... src/rend/RenderTexture.i"
	@echo "... src/rend/RenderTexture.s"
	@echo "... src/rend/Shader.o"
	@echo "... src/rend/Shader.i"
	@echo "... src/rend/Shader.s"
	@echo "... src/rend/Texture.o"
	@echo "... src/rend/Texture.i"
	@echo "... src/rend/Texture.s"
	@echo "... src/rend/Utilities.o"
	@echo "... src/rend/Utilities.i"
	@echo "... src/rend/Utilities.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

